version: '2'
services:
    healthmap-app:
        image: healthmap
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://healthmap-mysql:3306/healthmap?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=healthmap-elasticsearch:9300
        ports:
            - 8080:8080
    healthmap-mysql:
        extends:
            file: mysql.yml
            service: healthmap-mysql
    healthmap-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: healthmap-elasticsearch
